version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 444842782536.dkr.ecr.ap-south-1.amazonaws.com)
  build:
    commands:
      - docker build -t youtube:latest .
      - docker tag youtube:latest 444842782536.dkr.ecr.ap-south-1.amazonaws.com/youtube:latest
  post_build:
    commands:
      - docker push 444842782536.dkr.ecr.ap-south-1.amazonaws.com/youtube:latest
      - printf '[{"name":demotask,"imageUri":"%s"}]' 444842782536.dkr.ecr.ap-south-1.amazonaws.com/youtube:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
